[tool.poetry]
name = "poetry add fastapi uvicorn"
version = "0.1.0"
description = ""
authors = ["ishrak_abir  <aatharishrak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
